# Site settings
title: Matters in Media Art 媒體藝術事務
email: info@matters-in-media-art.org
description: 一個多階段的合作計畫，旨在為媒體藝術的保存提供指南。此翻譯網站內容是由科技藝術典藏基礎計畫承擔的一個獨立計畫。
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://mma-zh.savemediaart.tw" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
